version: "3.8"

x-default-environment: &default-environment
  POSTGRES_DB: ${POSTGRES_DB:-collector_db}
  POSTGRES_USER: ${POSTGRES_USER:-collector}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}

services:

  collector:
    container_name: collector
    image: collector-service
    build:
      context: collector

    hostname: ${COLLECTOR_HOST:-collector}
    ports:
      - ${COLLECTOR_PORT:-8080}:8000

    environment:
      <<: *default-environment
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

    depends_on:
      - postgres

    volumes:
      - "collector_data:/data"

    command: uvicorn main:app --port 8000

  postgres:
    image: postgres:latest
    container_name: postgres

    hostname: ${POSTGRES_HOST:-postgres}
    ports:
      - ${POSTGRES_PORT-5432}:5432

    environment:
      <<: *default-environment

    volumes:
      - "pg_data:/data"

volumes:
  collector_data:
  pg_data: