version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "collector_db"
      POSTGRES_USER: "collector"
      POSTGRES_PASSWORD: "collector_password"
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/data"

volumes:
  pg_data: